import os
from dotenv import load_dotenv
from app.services.llm_service import get_llm
from app.services.vector_service import get_retriever
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage
from langchain_core.tools import tool
from app.tools.search_friend import search_friends
from app.tools.send_message_tool import send_message

# Load environment variables
load_dotenv()

DB_DIR = "chroma_db"
global_llm = None
global_retriever = None

@tool
def search_friends_tool(name: str) -> str:
    """
    Search for friends/users in the chat application by their username.
    Use this tool when the user mentions wanting to send a message to a user or searching for a user.
    Returns a string containing a list of matching users, including their IDs.
    """
    return search_friends(name)

@tool
def send_message_tool(message: str, receiver_id: str, sender_id: str) -> str:
    """
    Send a message to a user/friend.
    You must provide:
    - message: the content of the message to send
    - receiver_id: the ID of the recipient user (get this by first calling search_friends_tool)
    - sender_id: the ID of the current user sending the message
    Returns a status string indicating if the message was sent successfully.
    """
    return send_message(message=message, sender_id=sender_id, receiver_id=receiver_id)

def init_rag():
    global global_llm, global_retriever
    
    # 1. Initialize LLM from service
    try:
        global_llm = get_llm()
    except Exception as e:
        print(f"Error loading LLM service: {e}")
        global_llm = None

    # 2. Get retriever from service if DB exists
    global_retriever = None
    if os.path.exists(DB_DIR):
        try:
            global_retriever = get_retriever(persist_directory=DB_DIR)
        except Exception as e:
            print(f"Error initializing vector database: {e}")

# Format docs helper
def format_docs(docs):
    if not docs:
        return "No relevant FAQ context found."
    return "\n\n".join(doc.page_content for doc in docs)

# Initialize on module import
init_rag()

def ask_question(message: str, sender_id: str = None) -> str:
    """
    Accepts a user query, searches the vector database for relevant FAQs, 
    and returns a conversational answer generated by Groq LLM, utilizing
    tools for sending messages and searching friends if needed.
    """
    global global_llm, global_retriever
    
    # Lazy reload vector store if it wasn't initialized initially
    if global_llm is None or (os.path.exists(DB_DIR) and global_retriever is None):
        init_rag()
        
    if not global_llm:
        return "I'm sorry, the chatbot helper service is currently offline. Please check back later!"
        
    try:
        # Bind tools to the LLM
        tools = [search_friends_tool, send_message_tool]
        llm_with_tools = global_llm.bind_tools(tools)
        
        # Retrieve FAQ context
        formatted_context = "No FAQ context available."
        if global_retriever:
            try:
                docs = global_retriever.invoke(message)
                formatted_context = format_docs(docs)
            except Exception as e:
                print(f"Error retrieving context: {e}")
                
        # System prompt with instructions
        system_prompt_text = (
            "You are 'Bubble', the friendly, warm, and helpful AI assistant for the Bubble chatting/messaging app.\n"
            "Your goal is to assist users with their questions about the Bubble app using the provided context from our FAQs.\n\n"
            "Here are the rules you must follow:\n"
            "1. Be concise, polite, and conversational.\n"
            "2. Use the provided context (FAQs) if it is relevant to the user's question.\n"
            "3. If the context does not answer the question, or if the question is general (e.g., greetings, how are you, etc.), "
            "answer politely using your general knowledge, keeping in character as Bubble's assistant.\n"
            "4. Do NOT mention words like 'context', 'retrieved documents', 'FAQ database', or similar. Make your answers feel direct and natural.\n"
            "5. If the user wants to send a message (e.g., 'send hi to Hemant' or 'say hello to ishant'), you MUST call the tools to perform this request.\n"
            "   - First, call search_friends_tool with the recipient's name to find their receiver_id.\n"
            "   - Once you get the search results containing the recipient's ID, call send_message_tool with the message, receiver_id, and the sender_id.\n"
            "   - If no user is found or there are multiple matches, ask the user to clarify.\n"
            "   - Note: The current user's ID (sender_id) is: {sender_id}.\n"
            "   - If the sender_id is not available (i.e. 'None' or empty), politely ask the user for their sender ID or inform them you cannot send the message without it.\n\n"
            "Retrieved FAQ Context:\n"
            "{context}"
        )
        
        sys_message = SystemMessage(content=system_prompt_text.format(
            sender_id=sender_id or "None",
            context=formatted_context
        ))
        
        messages = [sys_message, HumanMessage(content=message)]
        
        tool_map = {
            "search_friends_tool": search_friends_tool,
            "send_message_tool": send_message_tool
        }
        
        max_iterations = 5
        for _ in range(max_iterations):
            response = llm_with_tools.invoke(messages)
            messages.append(response)
            
            if not response.tool_calls:
                return response.content
                
            for tool_call in response.tool_calls:
                tool_name = tool_call["name"]
                tool_args = tool_call["args"]
                tool_id = tool_call["id"]
                
                if tool_name in tool_map:
                    try:
                        tool_output = tool_map[tool_name].invoke(tool_args)
                    except Exception as tool_err:
                        tool_output = f"Error executing tool {tool_name}: {str(tool_err)}"
                else:
                    tool_output = f"Tool {tool_name} is not available."
                    
                messages.append(ToolMessage(content=str(tool_output), tool_call_id=tool_id))
                
        # If we exceed max_iterations, return the content of the last AI message
        return response.content
        
    except Exception as e:
        print(f"Error in RAG service ask_question: {e}")
        return "I'm sorry, I encountered an error while processing your request. Please try again in a moment!"
