import os
from dotenv import load_dotenv
from app.services.llm_service import get_llm
from app.services.vector_service import get_retriever
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Load environment variables
load_dotenv()

DB_DIR = "chroma_db"
rag_chain = None

def init_rag():
    global rag_chain
    
    # 1. Initialize LLM from service
    try:
        llm = get_llm()
    except Exception as e:
        print(f"Error loading LLM service: {e}")
        llm = None

    # 2. Get retriever from service if DB exists
    retriever = None
    if os.path.exists(DB_DIR):
        try:
            retriever = get_retriever(persist_directory=DB_DIR)
        except Exception as e:
            print(f"Error initializing vector database: {e}")

    # 3. Define system prompt template
    system_prompt = (
        "You are 'Bubble', the friendly, warm, and helpful AI assistant for the Bubble chatting/messaging app.\n"
        "Your goal is to assist users with their questions about the Bubble app using the provided context from our FAQs.\n\n"
        "Here are the rules you must follow:\n"
        "1. Be concise, polite, and conversational.\n"
        "2. Use the provided context (FAQs) if it is relevant to the user's question.\n"
        "3. If the context does not answer the question, or if the question is general (e.g., greetings, how are you, etc.), "
        "answer politely using your general knowledge, keeping in character as Bubble's assistant.\n"
        "4. Do NOT mention words like 'context', 'retrieved documents', 'FAQ database', or similar. Make your answers feel direct and natural.\n\n"
        "Retrieved FAQ Context:\n"
        "{context}\n\n"
        "User Question: {question}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt)
    ])

    # 4. Define formatting helper
    def format_docs(docs):
        if not docs:
            return "No relevant FAQ context found."
        return "\n\n".join(doc.page_content for doc in docs)

    # 5. Build RAG chain
    if llm:
        if retriever:
            rag_chain = (
                {"context": retriever | format_docs, "question": RunnablePassthrough()}
                | prompt
                | llm
                | StrOutputParser()
            )
        else:
            rag_chain = (
                {"context": lambda x: "No FAQ context available.", "question": RunnablePassthrough()}
                | prompt
                | llm
                | StrOutputParser()
            )
    else:
        rag_chain = None

# Initialize on module import
init_rag()

def ask_question(message: str) -> str:
    """
    Accepts a user query, searches the vector database for relevant FAQs, 
    and returns a conversational answer generated by Groq LLM.
    """
    global rag_chain
    
    # Lazy reload vector store if it wasn't initialized initially (e.g. database was created after import)
    if rag_chain is None or (os.path.exists(DB_DIR) and "RunnablePassthrough" not in str(rag_chain)):
        # Re-initialize only if there is a DB available now but we didn't have one before
        init_rag()
        
    if not rag_chain:
        return "I'm sorry, the chatbot helper service is currently offline. Please check back later!"
        
    try:
        response = rag_chain.invoke(message)
        return response
    except Exception as e:
        print(f"Error in RAG service ask_question: {e}")
        return "I'm sorry, I encountered an error while processing your request. Please try again in a moment!"
